name: ci
on:
  push:
    branches:
      - 'main'
  pull_request: {}
jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout step
        uses: actions/checkout@v2
      - name: use Node.js
        uses: actions/setup-node@v2
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: ZAP DAST Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: http://flask-app-319191450.us-east-2.elb.amazonaws.com/
      - name: dockerize
        run: |
          docker build -t sample:env .
          echo "::set-output name=image::sample:env"
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: sample:env
          args: --file=Dockerfile
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
